server:
  port: 8082

spring:
  application:
    name: my-second-service

eureka:
  instance:
    hostname: localhost
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
